TCDIST_VM_FILES+=$(TCDIST_DIR)/br_secure/vm_2.sh
TCDIST_VM_FILES+=$(TCDIST_OUTPUT)/br_secure/br_secure_$(TCDIST_ARCH)_$(TCDIST_PLATFORM).ext2
TCDIST_VM_FILES+=$(TCDIST_OUTPUT)/br_secure/br_secure_$(TCDIST_ARCH)_$(TCDIST_PLATFORM).$(TCDIST_KERNEL_IMAGE_FILE)
TCDIST_VM_FILES+=$(TCDIST_OUTPUT)/br_secure/br_secure.mac
