#!/bin/bash
# Disable shellcheck complaints about unused variables, we know these will be used
# shellcheck disable=SC2034

# Do not insert whitespace before variable names,
# keep assignments at the start of the line!

# Platform selection (raspi4 or x86)
PLATFORM=raspi4

# Sub platform selection, only valid for x86 (intel or amd), leave blank
# for others
SUB_PLATFORM=

# Hypervisor selection (xen or kvm)
HYPERVISOR=xen

# BUILDOPT defines type of build
# 'usb' for USB build
# 'mmc' for MMC/SD build
# 'dhcp' for dynamic network configuration tftp/nfsroot build
# 'static' for static network configuration tftp/nfsroot build
BUILDOPT=usb

# SECURE_OS defines if we are building a secure-os or not
SECURE_OS=0

# SUDOTYPE selects the way sudo command/function is used
# 'standard' will use standard sudo executable as it is
# 'showonpassword' will show command to be run when password is prompted
# 'verbose' will show all sudoed commands even if password is not needed
# 'confirm' will show and confirm all sudoed commands
SUDOTYPE=showonpassword

# Update bootfs/rootfs/domufs only, do not wipe (rm -rf) contents
FS_UPDATE_ONLY=0

# Automount sd/usb if not mounted when doing e.g. rootfs (0=off, 1=on)
AUTOMOUNT=0

# Default device for mount operations
DEFDEV=/dev/sda

# Device tree used
DEVTREE=bcm2711-rpi-4-b.dtb

# 0 = load device tree in u-boot, 1 = use firmware provided device tree
FWFDT=0

# API key for downloading binaries etc. from Artifactory
# Generate key from JFrog and place it into the .setup_sh_config file
ARTIFACTORY_API_KEY=

# Path where downloads are cached. If empty cache is not used.
DOWNLOAD_CACHE_DIR="$(pwd)/.download_cache"

# Directories where partitions are mounted
MNT_DIR="$(pwd)/mnt"
BOOTMNT="$MNT_DIR/bootfs"
ROOTMNT="$MNT_DIR/rootfs"
DOMUMNT="$MNT_DIR/domufs"

# Where guest kernels are built by default
GKBUILD="$(pwd)/images"

# Where filesystem dirs are generated to and where disk image is placed
IMGBUILD="$(pwd)/images/genimage"

# Temporary directory
TMPDIR="$(pwd)/images/tmp"

# Where buildroot is storing images
IMAGES="$(pwd)/buildroot/output/images"
KERNEL_IMAGE="${IMAGES}/Image"

# ccache options
CCACHE="$(command -v ccache || true)"
CCACHE_DIR="$(pwd)/.ccache"
CCACHE_MAXSIZE=10G

# Xen cpu and memory options
XEN_DOM0_CPUCOUNT=2
XEN_DOM0_MEMORY=4G

# RasPi dom0 static IP Configuration
DEVICEIP=192.168.1.170
DEVICENM=255.255.255.0
DEVICEGW=192.168.1.1

# These settings should be valid both in DHCP and static IP configurations
DEVICEDNS=1.1.1.1
DEVICEHN=raspi

# TFTP and NFS server settings
TFTPSERVER=192.168.1.145
TFTPPATH=/srv/tftp
NFSSERVER="$TFTPSERVER"
NFSDOM0=/srv/nfsdom0
NFSDOMU=/srv/nfsdomu

