TCDIST_VM_FILES+=$(TCDIST_DIR)/br_conn/vm_1.sh
TCDIST_VM_FILES+=$(TCDIST_OUTPUT)/br_conn/br_conn_$(TCDIST_ARCH)_$(TCDIST_PLATFORM).ext2
TCDIST_VM_FILES+=$(TCDIST_OUTPUT)/br_conn/br_conn_$(TCDIST_ARCH)_$(TCDIST_PLATFORM).$(TCDIST_KERNEL_IMAGE_FILE)
TCDIST_VM_FILES+=$(TCDIST_OUTPUT)/br_conn/br_conn.mac_1
TCDIST_VM_FILES+=$(TCDIST_OUTPUT)/br_conn/br_conn.mac_2
