#!/bin/bash
# Disable shellcheck complaints about unused variables, we know these will be used
# shellcheck disable=SC2034

# Do not insert whitespace before variable names,
# keep assignments at the start of the line!

# Name for project (used as output filename prefix also)
TCDIST_NAME="tc_distro"

# HW architechture (x86|arm64)
TCDIST_ARCH=x86

# Platform selection (raspi4 | qemu | ls1012afrwy)
TCDIST_PLATFORM=upxtreme

# Sub architecture selection, currently valid for x86 (intel or amd), leave blank
# for others
TCDIST_SUB_ARCH=intel

# Hypervisor selection (xen or kvm)
TCDIST_HYPERVISOR=kvm

# Enable for system testing build. This contains some extra testing tools,
# like avocado-framework.
TCDIST_SYS_TEST=0

# Default linux branch for the build for both buildroot and guest-os setups.
# 'xen' is used for raspi4 for now, but should be renamed later once the branch
# for it is updated. For x86 builds, this should be of form tc-x86-5.10-dev;
# and running x86config sets it properly.
TCDIST_LINUX_BRANCH=tc-x86-5.10-sec

# TCDIST_VMLIST is list of all selected VMs for system image
# Admin is always first and connection VM second, rest can be arranged freely
TCDIST_VMLIST=br_admin

# Internal network address, three octets
TCDIST_INTERNAL_NET=10.10.10

# Change this to point your wired external network interface device
# Used for setting up bridging for admin machine
TCDIST_ETHDEV="eth0"

# Bridge name used for bridging admin machine
TCDIST_ADMIN_BRIDGE="adminbr0"

# TCDIST_SUDOTYPE selects the way sudo command/function is used
# 'standard' will use standard sudo executable as it is
# 'showonpassword' will show command to be run when password is prompted
# 'verbose' will show all sudoed commands even if password is not needed
# 'confirm' will show and confirm all sudoed commands
TCDIST_SUDOTYPE=showonpassword

# Device tree used
TCDIST_DEVTREE=

# API key for downloading binaries etc. from Artifactory
# Generate key from JFrog and place it into the .setup_sh_config file
TCDIST_ARTIFACTORY_API_KEY=

# Path where downloads are cached. If empty cache is not used.
TCDIST_DL_CACHE_DIR="$(pwd)/.download_cache"

# Temporary directory
TCDIST_TMPDIR="${TCDIST_OUTPUT}/tmp"

# kernel image filename usually: bzImage | Image
TCDIST_KERNEL_IMAGE_FILE=bzImage

# Device IP address
TCDIST_DEVICEIP=192.168.1.170

# These settings should be valid both in DHCP and static IP configurations
TCDIST_DEVICEDNS=1.1.1.1

# ccache options
CCACHE="$(command -v ccache || true)"
CCACHE_DIR="${TCDIST_OUTPUT}/.ccache"
CCACHE_MAXSIZE=10G

